import type { Metadata } from "next";
import { PolicyLayout } from "@/components/policy-layout";

export const metadata: Metadata = { title: "Privacy Notice", description: "Website privacy information for Restore Healthcare Solutions Limited." };

export default function PrivacyPage() {
  return <PolicyLayout title="Privacy notice" intro="This is a website-ready privacy framework for Restore Healthcare Solutions Limited. It should be reviewed and updated with confirmed contact details, processing systems and professional advice before the website accepts personal or care information.">
    <section><h2>1. Who we are</h2><p>Restore Healthcare Solutions Limited is a healthcare and support organisation based at 53 Phibblestown Wood, Dublin 15, D15 R5DE, Ireland. For the purposes of applicable data-protection law, Restore may act as a data controller when it determines why and how personal information is processed.</p></section>
    <section><h2>2. Information this website may collect</h2><p>The current website is informational and does not include an online care-enquiry, recruitment or payment form. Standard technical information may still be processed when someone visits, such as browser type, device information, approximate location derived from an IP address, pages viewed and security logs.</p><p>If a visitor later contacts Restore by telephone or email, information voluntarily provided may include contact details and the nature of the enquiry. Health or care information should only be requested and processed where a clear lawful basis and appropriate safeguards have been established.</p></section>
    <section><h2>3. Why information may be used</h2><ul><li>To respond to a direct enquiry.</li><li>To keep the website secure and functioning correctly.</li><li>To understand general website usage where consent is required and obtained.</li><li>To meet legal, regulatory or safeguarding responsibilities.</li></ul></section>
    <section><h2>4. Lawful bases</h2><p>Depending on the context, processing may rely on consent, steps requested before entering a contract, performance of a contract, compliance with a legal obligation, protection of vital interests or legitimate interests that do not override individual rights. Additional conditions are required before special-category data such as health information is processed.</p></section>
    <section><h2>5. Sharing and storage</h2><p>Personal information should only be shared with authorised staff and carefully selected service providers where necessary. Information should not be sold. Appropriate contractual, security and transfer safeguards should be used whenever another organisation processes information for Restore.</p></section>
    <section><h2>6. Retention</h2><p>Information should be kept only for as long as required for the purpose for which it was collected, including any legal, safeguarding, insurance or contractual retention period. Confirmed retention schedules will take precedence over this general statement.</p></section>
    <section><h2>7. Individual rights</h2><p>Subject to applicable law, individuals may have rights to access, correct, erase or restrict the use of their information, object to certain processing, receive portable information and withdraw consent. They may also raise a concern with Ireland’s Data Protection Commission.</p></section>
    <section><h2>8. Contact</h2><p>Restore’s confirmed privacy email address and telephone number will be added before interactive data collection is enabled. Postal correspondence may be sent to the organisation’s Dublin 15 address.</p></section>
  </PolicyLayout>;
}
